/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if ((_MSC_VER) || (HAVE_PRAGMA_PACK))
#pragma pack (push,OBJECT_ALIGNMENT)
#endif

#ifndef UDISCORDMANAGER_API
#define UDISCORDMANAGER_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern UDISCORDMANAGER_API FName UDISCORDMANAGER_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif

#ifndef NAMES_ONLY
class UDISCORDMANAGER_API AUDiscordManager : public AActor
{
public:
    BITFIELD bInitialized : 1 GCC_PACK(INT_ALIGNMENT);

    DECLARE_FUNCTION(execinitDiscord);
    DECLARE_FUNCTION(execinitActivity);
    DECLARE_FUNCTION(execupdateAcitivty);
    DECLARE_FUNCTION(execclearActivity);
    DECLARE_FUNCTION(execopenGuildInvite);
    DECLARE_FUNCTION(execrunCallbacks);

    DECLARE_CLASS(AUDiscordManager, AActor, 0, UDiscordManager);
    AUDiscordManager();
};
#endif

AUTOGENERATE_FUNCTION(AUDiscordManager, -1, execinitDiscord);
AUTOGENERATE_FUNCTION(AUDiscordManager, -1, execinitActivity);
AUTOGENERATE_FUNCTION(AUDiscordManager, -1, execupdateAcitivty);
AUTOGENERATE_FUNCTION(AUDiscordManager, -1, execclearActivity);
AUTOGENERATE_FUNCTION(AUDiscordManager, -1, execopenGuildInvite);
AUTOGENERATE_FUNCTION(AUDiscordManager, -1, execrunCallbacks);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif // NAMES_ONLY

#if ((_MSC_VER) || (HAVE_PRAGMA_PACK))
#pragma pack (pop)
#endif

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_SIZE_NODIE(AUDiscordManager)
#endif // VERIFY_CLASS_SIZES